#!/usr/bin/env python3
from __future__ import annotations

"""
Build context<TAB>completion pairs from ronantakizawa/github-top-code for world/decoder training.

Usage:
  pip install datasets
  python scripts/prepare_github_top_code.py --output data/github_top_code_pairs.txt
  python scripts/prepare_github_top_code.py --output data/rust_code_pairs.txt --languages Rust --max-files 50000
  python scripts/prepare_github_top_code.py --output data/multilang_pairs.txt --default-languages --max-files 200000

Output format: one line per pair, prefix<TAB>completion (TAB in content is replaced by spaces).
"""

# Default language set for --default-languages (file_language values in ronantakizawa/github-top-code)
DEFAULT_LANGUAGES = [
    "Rust",
    "TypeScript",
    "Go",
    "JavaScript",
    "C/C++ Header",
    "C",
    "C++",
    "TSX",
    "CSS",
    "HTML",
]

import argparse
import hashlib
import re
from collections import defaultdict
from pathlib import Path


def slugify_language(language: str) -> str:
    slug = language.strip().lower()
    slug = re.sub(r"[^a-z0-9]+", "_", slug)
    return slug.strip("_") or "code"


def escape_pair_field(text: str) -> str:
    return (
        text.replace("\\", "\\\\")
        .replace("\r", "")
        .replace("\t", "    ")
        .replace("\n", "\\n")
        .strip()
    )


def looks_generated(content: str) -> bool:
    sample = "\n".join(content.splitlines()[:12]).lower()
    markers = [
        "generated by",
        "auto-generated",
        "automatically generated",
        "do not edit",
        "@generated",
    ]
    return any(marker in sample for marker in markers)


def looks_minified(content: str) -> bool:
    lines = content.splitlines()
    if not lines:
        return True
    max_line_len = max(len(line) for line in lines)
    avg_line_len = sum(len(line) for line in lines) / max(len(lines), 1)
    return max_line_len > 600 or avg_line_len > 160


def normalize_code_field(text: str, language: str, tag: str) -> str:
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = text.replace("\t", "    ").strip()
    return f"<lang:{slugify_language(language)}> <{tag}>\\n{escape_pair_field(text)}"


def split_file_into_pairs(
    content: str,
    language: str,
    *,
    min_lines_prefix: int = 2,
    min_lines_completion: int = 2,
    split_ratio: float = 0.5,
) -> list[tuple[str, str]]:
    """Split a single file's content into (prefix, completion) pairs.
    Uses line count; split_ratio is fraction of lines in prefix (rest = completion).
    """
    lines = content.splitlines()
    if len(lines) < min_lines_prefix + min_lines_completion:
        return []
    n = len(lines)
    cut = max(min_lines_prefix, min(round(n * split_ratio), n - min_lines_completion))
    if cut < min_lines_prefix or (n - cut) < min_lines_completion:
        return []
    prefix = "\n".join(lines[:cut]).strip()
    completion = "\n".join(lines[cut:]).strip()
    if not prefix or not completion:
        return []
    return [
        (
            normalize_code_field(prefix, language, "ctx"),
            normalize_code_field(completion, language, "reply"),
        )
    ]


def run(
    output_path: Path,
    *,
    split: str = "train",
    languages: list[str] | None = None,
    max_files: int | None = None,
    min_lines: int = 5,
    min_lines_prefix: int = 2,
    min_lines_completion: int = 2,
    split_ratio: float = 0.5,
) -> int:
    try:
        from datasets import load_dataset
    except ImportError as e:
        raise RuntimeError("Install: pip install datasets") from e

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    ds = load_dataset("ronantakizawa/github-top-code", split=split)
    if languages:
        lang_set = {l.strip() for l in languages}
        ds = ds.filter(lambda x: (x.get("file_language") or "").strip() in lang_set)

    per_language_limit = None
    if languages and max_files:
        per_language_limit = max(1, max_files // max(len(languages), 1))

    written = 0
    seen_hashes: set[str] = set()
    language_counts: dict[str, int] = defaultdict(int)
    with open(output_path, "w", encoding="utf-8") as f:
        for i, row in enumerate(ds):
            if max_files is not None and written >= max_files:
                break
            language = (row.get("file_language") or "").strip() or "Code"
            if per_language_limit is not None and language_counts[language] >= per_language_limit:
                continue
            content = (row.get("content") or "").strip()
            if not content:
                continue
            if looks_generated(content) or looks_minified(content):
                continue
            lines = content.splitlines()
            if len(lines) < min_lines:
                continue
            for prefix, completion in split_file_into_pairs(
                content,
                language,
                min_lines_prefix=min_lines_prefix,
                min_lines_completion=min_lines_completion,
                split_ratio=split_ratio,
            ):
                digest = hashlib.sha1(f"{prefix}\t{completion}".encode("utf-8")).hexdigest()
                if digest in seen_hashes:
                    continue
                seen_hashes.add(digest)
                line = f"{prefix}\t{completion}\n"
                f.write(line)
                written += 1
                language_counts[language] += 1
                if per_language_limit is not None and language_counts[language] >= per_language_limit:
                    break

    return written


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Build code pairs from ronantakizawa/github-top-code (context TAB completion)."
    )
    ap.add_argument(
        "--output",
        type=Path,
        default=Path("data/github_top_code_pairs.txt"),
        help="Output .txt path (default: data/github_top_code_pairs.txt)",
    )
    ap.add_argument(
        "--split",
        default="train",
        choices=("train", "test", "validation"),
        help="Dataset split (default: train)",
    )
    ap.add_argument(
        "--languages",
        nargs="*",
        default=None,
        help="Filter by file_language (e.g. Rust TypeScript Go). Default: all.",
    )
    ap.add_argument(
        "--default-languages",
        action="store_true",
        help="Use preset: Rust, TypeScript, Go, JavaScript, C/C++ Header, C, C++, TSX, CSS, HTML.",
    )
    ap.add_argument(
        "--max-files",
        type=int,
        default=None,
        help="Max number of source files to process (default: all)",
    )
    ap.add_argument(
        "--min-lines",
        type=int,
        default=5,
        help="Skip files with fewer lines (default: 5)",
    )
    ap.add_argument(
        "--min-lines-prefix",
        type=int,
        default=2,
        help="Min lines in prefix (default: 2)",
    )
    ap.add_argument(
        "--min-lines-completion",
        type=int,
        default=2,
        help="Min lines in completion (default: 2)",
    )
    ap.add_argument(
        "--split-ratio",
        type=float,
        default=0.5,
        help="Fraction of lines in prefix, rest completion (default: 0.5)",
    )
    args = ap.parse_args()
    languages = args.languages
    if args.default_languages:
        languages = DEFAULT_LANGUAGES
    n = run(
        args.output,
        split=args.split,
        languages=languages,
        max_files=args.max_files,
        min_lines=args.min_lines,
        min_lines_prefix=args.min_lines_prefix,
        min_lines_completion=args.min_lines_completion,
        split_ratio=args.split_ratio,
    )
    print(f"Wrote {n} pairs to {args.output}")


if __name__ == "__main__":
    main()
